name: Create Lambda Function

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4  # Use the version of Terraform you want

   
    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform

    - name: Plan Terraform changes
      run: terraform plan -out=tfplan
      working-directory: ./terraform

    - name: Apply Terraform changes
      run: terraform apply tfplan
      working-directory: ./terraform
      env:
        TF_INPUT: 0  # To avoid the need for user input during apply


    - name: Show outputs
      run: terraform output -json
      working-directory: ./terraform
