name: Create Lambda Function

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.4  # Use the version of Terraform you want
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAZ5G533XB2UMZCQ35
        aws-secret-access-key: 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
        aws-region: ap-south-1  # Adjust the region as needed


   
    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform changes
      run: terraform plan -out=tfplan

    - name: Apply Terraform changes
      run: terraform apply tfplan
      env:
        TF_INPUT: 0  # To avoid the need for user input during apply


    - name: Show outputs
      run: terraform output -json
      working-directory: ./terraform
