name: createlambdafunction

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Terraform
        run: terraform init

      - name: Deploy Lambda function
        run: terraform apply 
